name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pages: write
            id-token: write

        steps:
            - name: Checkout repository
              id: idmain
              uses: actions/checkout@v4
            #   with:
            #       path: github-pages-app

            - name: Checkout database repository
              id: iddb
              uses: actions/checkout@v4
              with:
                  repository: royfordland/github-pages-app-db
                  path: github-pages-app-db

            # temp: print the paths
            - name: TEMP Log Repository Paths
              run: |
                  echo "main repo absolute path: ${{ steps.idmain.outputs.path }}"
                  echo "database repo absolute path: ${{ steps.iddb.outputs.path }}"

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
                  cache-dependency-path: package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Build production bundle
              run: npm run build -- --configuration production --base-href /github-pages-app/

            - name: Configure GitHub Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact for GitHub Pages
              uses: actions/upload-pages-artifact@v4
              with:
                  path: dist/github-pages-app/browser

            - name: Deploy Pages
              uses: actions/deploy-pages@v4
